sample_payload: 'sample_payload.json'
EXPT_DIR : "./log"
LOG_DIR : "./log"
DATA_DIR : "./data_pascal_voc_2007/VOCdevkit/VOC2007"
WEIGHTS_DIR : "./weights"
exp_name: "yolov5-coco"
weightsclear: True

### TRAIN FUNCTION ARGS ###
onprem: True
train_epochs: 20
batch_size: 64
lr: 0.1
wtd: 0.0001
momentum: 0.9
use_cuda: True
