EXPT_DIR : "./log"
LOG_DIR : "./log"
DATA_DIR : "./data"
WEIGHTS_DIR : "./weights"
exp_name: "image_classification"
weightsclear: True

### TRAIN FUNCTION ARGS ###
onprem: True
train_epochs: 5
batch_size: 2
model_backbone: resnet18  # [resnet18, resnet34, resnet50, resnet101]
lr: 0.1
wtd: 0.0001
momentum: 0.9
device: cpu # [cpu, cuda]
verbose: True
