EXPT_DIR : "./log"
LOG_DIR : "./log"
DATA_DIR : "./data"
WEIGHTS_DIR : "./weights"
exp_name: "weather_classification"
weightsclear: True

### TRAIN FUNCTION ARGS ###
onprem: True
train_epochs: 10
batch_size: 2
lr: 0.1
wtd: 0.0001
momentum: 0.9
